name: BMS Ticket Monitor

on:
  # schedule:
  #   - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  check-tickets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager mailersend

      - name: Run monitor script
        run: python monitor.py
